// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:823313102959:web:da5b0fa1328560ce49f59a',
    messagingSenderId: '823313102959',
    projectId: 'pushnotification-2f67d',
    authDomain: 'pushnotification-2f67d.firebaseapp.com',
    storageBucket: 'pushnotification-2f67d.firebasestorage.app',
    measurementId: 'G-DYHFD6WE3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tfVdpom61OwUmzfAaqMQsLvTUYIY3kU',
    appId: '1:823313102959:android:38c1e37449fc4f8249f59a',
    messagingSenderId: '823313102959',
    projectId: 'pushnotification-2f67d',
    storageBucket: 'pushnotification-2f67d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:823313102959:ios:37af99efe17ede0649f59a',
    messagingSenderId: '823313102959',
    projectId: 'pushnotification-2f67d',
    storageBucket: 'pushnotification-2f67d.firebasestorage.app',
    iosBundleId: 'com.example.azaanRamzanTimings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:823313102959:ios:37af99efe17ede0649f59a',
    messagingSenderId: '823313102959',
    projectId: 'pushnotification-2f67d',
    storageBucket: 'pushnotification-2f67d.firebasestorage.app',
    iosBundleId: 'com.example.azaanRamzanTimings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:823313102959:web:5cf3a75fc3ac189949f59a',
    messagingSenderId: '823313102959',
    projectId: 'pushnotification-2f67d',
    authDomain: 'pushnotification-2f67d.firebaseapp.com',
    storageBucket: 'pushnotification-2f67d.firebasestorage.app',
    measurementId: 'G-MEDJ4ES5ZH',
  );
}
